import os
from pymongo import MongoClient


ALERGEN_DICT = {
    'dairy': ['milk',
              'milk chocolate',
              'whole milk',
              'condensed milk',
              'semi-skimmed milk',
              'butter',
              'double cream',
              'cream'
              'feta',
              'creme fraiche',
              'cheddar cheese',
              'heavy cream',
              'double cream',
              'sour cream',
              'mascarpone',
              'clotted cream'
              'single cream',
              'yogurt',
              'puff pastry',
              'ice cream',
              'mars bar',
              'stilton cheese',
              'cheese',
              'butter, softened',
              'ricotta',
              'gruyère',
              'gruyere cheese'
              'cubed feta cheese',
              'parmigiano-reggiano',
              'fromage frais',
              'ghee',
              'shredded monterey jack cheese',
              'cream cheese',
              'goats Cheese'
              'full fat yogurt'
              'mozzarella',
              'pecorino',
              'garlic sauce',
              'gouda cheese',
              'mozzarella balls',
              'brie',
              'greek yogurt',
              'shortening',
              'unsalted butter'
              'chilled butter',
              'monterey jack cheese',
              'colby jack cheese',
              'cheese curds',
              'parmesan',
              'paneer',
              'salted butter'
              'parmesan cheese'],
    'eggs': ['eggs',
             'egg yolks',
             'free-range eggs, beaten',
             'free-range egg, beaten',
             'egg',
             'egg white',
             'mayonnaise',
             'meringue nests',
             'puff pastry'],
    'seaFood': ['prawns',
                'tiger prawns'
                'oyster sauce',
                'oysters'
                'mussels',
                'worcestershire sauce',
                'monkfish',
                'baby squid',
                'fish stock',
                'mackerel',
                'clams'
                'white fish fillets',
                'king prawns',
                'white fish',
                'smoked haddock',
                'red snapper'
                'salmon',
                'smoked salmon'
                'thai fish sauce',
                'raw king prawns',
                'tuna',
                'salt cod',
                'anchovy fillet',
                'fish sauce',
                'pilchards',
                'haddock',
                'herring'],
    'nuts': ['cashew nuts',
             'cashews',
             'peanuts',
             'peanut cookies',
             'peanut butter'
             'pecan nuts',
             'peanut oil',
             'hazlenuts',
             'almond milk',
             'ground almonds'],
    'soy': ['soy sauce',
            'dark soy sauce',
            'soya milk'],
    'wheat': ['plain flour',
              'puff pastry',
              'vermicelli',
              'flour',
              'breadcrumbs',
              'self-raising flour',
              'self raising flour',
              'mars bar',
              'noodles',
              'pita bread',
              'penne rigate',
              'linguine pasta',
              'macaroni',
              'lasagne sheets',
              'flour',
              'baguette',
              'farfalle',
              'bowtie pasta',
              'fettuccine',
              'bread',
              'egg rolls',
              'rigatoni',
              'white flour',
              'mixed grain',
              'udon noodles',
              'pretzels',
              'whole wheat',
              'wholegrain bread',
              'sesame seed burger buns',
              'english muffins',
              'naan bread',
              'filo pastry',
              'paccheri pasta'
              'spaghetti'],
    'meat': ['ground beef',
             'lamb',
             'lamb kidney',
             'lamb mince',
             'lamb loin chops',
             'lamb shoulder',
             'chicken stock',
             'chicken breast',
             'lard',
             'goat meat',
             'prosciutto',
             'doner meat'
             'chicken',
             'bun',
             'bulgur wheat',
             'beef shin',
             'veal',
             'suet',
             'duck legs',
             'beef',
             'beef gravy',
             'beef fillet',
             'beef stock',
             'lean minced beef',
             'minced beef',
             'hot beef stock',
             'ham',
             'parma ham',
             'goose fat',
             'gelatine leafs',
             'sausages',
             'chorizo',
             'pork chops',
             'bacon',
             'kielbasa',
             'turkey mince',
             'beacon',
             'pork',
             'ground pork',
             'minced pork'
             'chicken legs',
             'chicken thighs',
             'beef brisket',
             'lamb leg',
             'duck sauce',
             'mincemeat',
             'oxtail',
             'italian fennel sausages']
}
